// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9OEgsss9DyqVUx0tovcqN8FSNiTes8U4',
    appId: '1:224293441768:web:2e65f32e99aff2596d395d',
    messagingSenderId: '224293441768',
    projectId: 'fir-learn-app-4d5d8',
    authDomain: 'fir-learn-app-4d5d8.firebaseapp.com',
    storageBucket: 'fir-learn-app-4d5d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_ImpwE58xZySwaBw4Q3K9bypORyq_XM',
    appId: '1:224293441768:android:33943dbc21f6c69d6d395d',
    messagingSenderId: '224293441768',
    projectId: 'fir-learn-app-4d5d8',
    storageBucket: 'fir-learn-app-4d5d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rc7QWn3QW0POTCTU_KiHaBmz8upNMRM',
    appId: '1:224293441768:ios:bbba25fa3f9a7a666d395d',
    messagingSenderId: '224293441768',
    projectId: 'fir-learn-app-4d5d8',
    storageBucket: 'fir-learn-app-4d5d8.appspot.com',
    iosBundleId: 'com.example.neufloLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rc7QWn3QW0POTCTU_KiHaBmz8upNMRM',
    appId: '1:224293441768:ios:558a4adbc90e70256d395d',
    messagingSenderId: '224293441768',
    projectId: 'fir-learn-app-4d5d8',
    storageBucket: 'fir-learn-app-4d5d8.appspot.com',
    iosBundleId: 'com.example.neufloLearn.RunnerTests',
  );
}
